= RELP Flooder library rlp_09

Simple but scalable RELP flooder library

== Features

- Simple to use
- Scales to as many threads as wanted

== Limitations

- Minimal failure tolerance, mostly meant for testing
- Limited usability outside specific testing situations
- No structured data support yet
- No TLS support yet
- No customizable record support yet
- Supports only RFC5424

== How to use

[sourcecode,java]
----
// Custom config, for rest see Configurations
RelpFlooderConfig relpFlooderConfig = new RelpFlooderConfig();
relpFlooderConfig.setAppname("different_appname");
RelpFlooder relpFlooder = new RelpFlooder(relpFlooderConfig);
relpFlooder.start();
relpFlooder.stop();

// All defaults
RelpFlooder relpFlooder = new RelpFlooder();
relpFlooder.start();
relpFlooder.stop();

// Get total record count
relpFlooder.getRecordsSent();
----

== Configurations


[cols="4"]
|===
|Configuration key|Setter|Default value|Usage

|hostname|setHostname(String hostname)|localhost|Sets hostname for the event
|appname|setAppname(String appname)|rlp_09|Sets used appname for the event
|target|setTarget(String target)|127.0.0.1|RELP target server
|port|setPort(int port)|1601|RELP target port
|threads|setThreads(int threads)|4|RELP Flooder thread count
|useTls|setUseTls(boolean useTls)|false|Is TLS used for connections
|payloadSize|setPayloadSize(int payloadSize)|10|Record payload size (excludes any headers)
|batchSize|setBatchSize(int batchSize)|1|How many events is sent in one batch

|===

== Contributing

You can involve yourself with our project by https://github.com/teragrep/rlp_09/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
----
